#!C:\Users\MOIN\ZimadZambharkar\ML,DL,DS,NLP, Projects\End-To-End-Machine-Learning-project-With-Mlflow\mllp\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
